springfox:
  documentation:
    swagger-ui:
      enabled: true

mapper-locations: classpath:mapper/**/*.xml

server:
  port: 9999
  servlet:
    context-path: /demo

spring:
  datasource:
    druid:
      url: jdbc:mysql://xxx:3306/common?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&connectTimeout=30000&socketTimeout=60000&serverTimezone=Asia/Shanghai
      username: root
      password: xxx
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      filters: stat

  redis:
    cluster:
      nodes: xxx:6379,xxx:6379
      max-redirects: 3
    password: xxx
    connect-timeout: 10000
    timeout: 10000
    client-type: lettuce

  kafka:
    bootstrap-servers: xxx:9092,xxx:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: kafka-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
